name: SimpleAuth
main: SimpleAuth\SimpleAuth
version: 2.1.0-map.3
api: [3.0.0-ALPHA7]
load: STARTUP
author: PocketMine Team
authors: [shoghicp, awzaw]
description: Prevents people from impersonating an account, requires registration and login when connecting.
website: https://github.com/PocketMine/SimpleAuth
commands:
 login:
  description: "Logs into an account"
  usage: "/login <password>"
  permission: simpleauth.command.login
 register:
  description: "Registers an account"
  usage: "/register <password>"
  permission: simpleauth.command.register
 link:
  description: "Links an account"
  usage: "/link <other account><other password>"
  permission: simpleauth.command.link
 unlink:
  description: "Unlinks linked accounts"
  usage: "/unlink"
  permission: simpleauth.command.unlink

permissions:
 simpleauth:
  default: op
  description: "Allows using everything SimpleAuth has"
  children:
   simpleauth.chat:
    description: "Allows using the chat while not being authenticated"
    default: false
   simpleauth.move:
    description: "Allows moving while not being authenticated"
    default: false
   simpleauth.lastid:
    description: "Allows authenticating using the last id when enabled in the config"
    default: true
   simpleauth.command:
    description: "Allows using SimpleAuth commands"
    default: true
    children:
     simpleauth.command.register:
      description: "Allows registering an account"
      default: true
     simpleauth.command.login:
      description: "Allows logging into an account"
      default: true
     simpleauth.command.link:
      description: "Allows linking to another account"
      default: true
     simpleauth.command.unlink:
      description: "Allows unlinking an account"
      default: true
